/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVE = 4;
  /** RegularExpression Id. */
  int T_RIGHT = 5;
  /** RegularExpression Id. */
  int T_LEFT = 6;
  /** RegularExpression Id. */
  int T_ROTATE = 7;
  /** RegularExpression Id. */
  int T_LOOK = 8;
  /** RegularExpression Id. */
  int T_DROP = 9;
  /** RegularExpression Id. */
  int T_FREE = 10;
  /** RegularExpression Id. */
  int T_PICK = 11;
  /** RegularExpression Id. */
  int T_POP = 12;
  /** RegularExpression Id. */
  int T_CHECK = 13;
  /** RegularExpression Id. */
  int T_BLOCKEDP = 14;
  /** RegularExpression Id. */
  int T_NOP = 15;
  /** RegularExpression Id. */
  int T_BLOCK = 16;
  /** RegularExpression Id. */
  int T_REPEAT = 17;
  /** RegularExpression Id. */
  int T_IF = 18;
  /** RegularExpression Id. */
  int T_DEFINE = 19;
  /** RegularExpression Id. */
  int T_TO = 20;
  /** RegularExpression Id. */
  int T_OUTPUT = 21;
  /** RegularExpression Id. */
  int T_END = 22;
  /** RegularExpression Id. */
  int T_BALLOONS = 23;
  /** RegularExpression Id. */
  int T_CHIPS = 24;
  /** RegularExpression Id. */
  int T_NORTH = 25;
  /** RegularExpression Id. */
  int T_EAST = 26;
  /** RegularExpression Id. */
  int T_WEST = 27;
  /** RegularExpression Id. */
  int T_SOUTH = 28;
  /** RegularExpression Id. */
  int NUMERO = 29;
  /** RegularExpression Id. */
  int DIGIT = 30;
  /** RegularExpression Id. */
  int NAME = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"MOVE\"",
    "\"RIGHT\"",
    "\"LEFT\"",
    "\"ROTATE\"",
    "\"LOOK\"",
    "\"DROP\"",
    "\"FREE\"",
    "\"PICK\"",
    "\"POP\"",
    "\"CHECK\"",
    "\"BLOCKEDP\"",
    "\"NOP\"",
    "\"BLOCK\"",
    "\"REPEAT\"",
    "\"IF\"",
    "\"DEFINE\"",
    "\"TO\"",
    "\"OUTPUT\"",
    "\"END\"",
    "\"B\"",
    "\"C\"",
    "\"N\"",
    "\"E\"",
    "\"W\"",
    "\"S\"",
    "<NUMERO>",
    "<DIGIT>",
    "<NAME>",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"!\"",
    "\":\"",
  };

}
